### ISSUE TITLE
Created Redmine 4.x compatible version - how to contribute

### ISSUE THREAD

**Issue by tgoeg** [keeps/redmine_email_notification_content_filter#12]
The subject pretty much says it all.
I adapted the plugin to work with our installation. I am not a professional ruby dev, but it does what it should :-)

Seeing that there are ages old pull requests: Is this repo still active?

**Comment by wapsi** [comment]
You can fork this project and commit your changes in your own (forked) repository, that does not need any approval from the original author.

Could you please do that, so I can also test your version for 4.x? :)

**Comment by taskula** [comment]
Since no response from author I decided to do a quick and dirty fork that works with 5.0.5

https://github.com/Hypernova-Oy/redmine_email_notification_content_filter

**Comment by tgoeg** [comment]
Sorry - I didn't have any resources to look into this.
But looking at your fork it is definitely a much better solution. Mine was really just a hack.
Thanks a lot for your time and effort!
